=== dreth/kdb-intellij-plugin/resources/plot-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://studio.kdb.org/plot/schema#",
  "title": "Plot configuration schema",
  "type": "object",
  "properties": {
    "title": {
      "$ref": "#/definitions/Label"
    },
    "id": {
      "type": "string"
    },
    "legend": {
      "$ref": "#/definitions/Legend"
    },
    "type": {
      "$ref": "#/definitions/ChartType"
    },
    "domainAxis": {
      "$ref": "#/definitions/DomainAxis"
    },
    "rangeAxis": {
      "$ref": "#/definitions/RangeAxis"
    },
    "grid": {
      "$ref": "#/definitions/Grid"
    },
    "backgroundColor": {
      "type": "string",
      "format": "color"
    },
    "plotBackgroundColor": {
      "type": "string",
      "format": "color"
    },
    "series": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Series"
      }
    },
    "padding": {
      "$ref": "#/definitions/RectangleInsets"
    },
    "size": {
      "$ref": "#/definitions/Size"
    }
  },
  "required": ["id"],
  "definitions": {
    "Series": {
      "type": "object",
      "properties": {
        "lineWidth": {
          "type": "number"
        },
        "color": {
          "type": "string",
          "format": "color"
        },
        "lineType" : {
          "$ref": "#/definitions/LineType"
        },
        "visibleInLegend": {
          "type": "boolean"
        },
        "show": {
          "type": "boolean"
        }
      }
    },
    "ChartType": {
      "type": "string",
      "enum": [
        "LINE",
        "STAIRCASE",
        "SCATTER"
      ]
    },
    "LineType": {
      "type": "string",
      "enum": [
        "SOLID",
        "DASHED",
        "DASH_DOT",
        "DOT_DOT"
      ]
    },
    "Label": {
      "type": "object",
      "properties": {
        "show": {
          "type": "boolean"
        },
        "text": {
          "type": "string"
        },
        "font": {
          "$ref": "#/definitions/Font"
        },
        "color": {
          "type": "string",
          "format": "color"
        }
      },
      "required": [
        "show"
      ]
    },
    "DomainAxis": {
      "type": "object",
      "properties": {
        "label": {
          "$ref": "#/definitions/Label"
        },
        "ticks": {
          "$ref": "#/definitions/Tick"
        },
        "axisLineColor": {
          "type": "string",
          "format": "color"
        },
        "tickMarkColor": {
          "type": "string",
          "format": "color"
        }
      }
    },
    "RangeAxis": {
      "allOf": [
        {
          "$ref": "#/definitions/DomainAxis"
        },
        {
          "properties": {
            "range": {
              "$ref": "#/definitions/Range"
            },
            "tickUnit": {
              "$ref": "#/definitions/TickUnit"
            }
          }
        }
      ]
    },
    "Range": {
      "type": "object",
      "properties": {
        "autoAdjust": {
          "type": "boolean"
        },
        "minimumRangeValue": {
          "type": "number"
        },
        "maximumRangeValue": {
          "type": "number"
        }
      },
      "required": [
        "autoAdjust"
      ]
    },
    "TickUnit": {
      "type": "object",
      "properties": {
        "autoSelection": {
          "type": "boolean"
        },
        "tickUnitValue": {
          "type": "number"
        }
      }
    },
    "Tick": {
      "type": "object",
      "properties": {
        "showTickLabels": {
          "type": "boolean"
        },
        "showTickMarks": {
          "type": "boolean"
        },
        "tickLabelFont": {
          "$ref": "#/definitions/Font"
        },
        "tickLabelColor": {
          "type": "string",
          "format": "color"
        }
      },
      "required": [
        "showTickLabels",
        "showTickMarks"
      ]
    },
    "Font": {
      "type": "object",
      "properties": {
        "size": {
          "type": "integer"
        },
        "attributes": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "PLAIN",
              "BOLD",
              "ITALIC"
            ]
          }
        },
        "font": {
          "type": "string"
        }
      },
      "required": [
        "size",
        "attributes",
        "font"
      ]
    },
    "Grid": {
      "type": "object",
      "properties": {
        "horizontal": {
          "type": "boolean"
        },
        "horizontalLineWidth": {
          "type": "number"
        },
        "horizontalLineColor": {
          "type": "string",
          "format": "color"
        },
        "horizontalLineType" : {
          "$ref": "#/definitions/LineType"
        },
        "vertical": {
          "type": "boolean"
        },
        "verticalLineWidth": {
          "type": "number"
        },
        "verticalLineColor": {
          "type": "string",
          "format": "color"
        },
        "verticalLineType" : {
          "$ref": "#/definitions/LineType"
        }
      }
    },
    "Position": {
      "type": "string",
      "enum": [
        "TOP",
        "BOTTOM",
        "LEFT",
        "RIGHT"
      ]
    },
    "RectangleInsets": {
      "type": "object",
      "properties": {
        "top": {
          "type": "number"
        },
        "left": {
          "type": "number"
        },
        "bottom": {
          "type": "number"
        },
        "right": {
          "type": "number"
        }
      },
      "required": [
        "top",
        "left",
        "bottom",
        "right"
      ]
    },
    "Legend": {
      "type": "object",
      "properties": {
        "show": {
          "type": "boolean"
        },
        "margin": {
          "$ref": "#/definitions/RectangleInsets"
        },
        "position": {
          "$ref": "#/definitions/Position"
        },
        "backgroundColor": {
          "type": "string",
          "format": "color"
        }
      },
      "required": [
        "show"
      ]
    },
    "Size": {
      "type": "object",
      "properties": {
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        }
      }
    }
  }
}

=== dreth/kdb-intellij-plugin/resources/blue-eagle-lines.json
{
  "type" : "LINE",
  "id": "Blue Eagle Lines",
  "title": {
    "show": true,
    "text": "",
    "font": {
      "font": "Helvetica",
      "size": 16,
      "attributes": [
        "PLAIN"
      ]
    }
  },
  "backgroundColor": "#FFFFFF",
  "plotBackgroundColor": "#FFFFFF",
  "domainAxis": {
    "label": {
      "show": false
    },
    "ticks": {
      "showTickLabels": true,
      "showTickMarks": true,
      "tickLabelColor": "#404040",
      "tickLabelFont": {
        "font": "Helvetica",
        "size": 16,
        "attributes": ["PLAIN"]
      }
    }
  },
  "rangeAxis": {
    "label": {
      "show": false
    },
    "ticks": {
      "showTickLabels": true,
      "showTickMarks": true,
      "tickLabelColor": "#404040",
      "tickLabelFont": {
        "font": "Helvetica",
        "size": 16,
        "attributes": ["PLAIN"]
      }
    },
    "range": {
      "autoAdjust": true
    },
    "tickUnit": {
      "autoSelection": true
    }
  },
  "grid": {
    "horizontal": true,
    "vertical": true,
    "horizontalLineColor": "#C0C0C0",
    "verticalLineColor": "#C0C0C0",
    "horizontalLineWidth": 0.5,
    "verticalLineWidth": 0.5,
    "horizontalLineType": "DASHED",
    "verticalLineType": "DASHED"
  },
  "legend": {
    "show": true,
    "backgroundColor": "#FFFFFF",
    "position": "BOTTOM",
    "margin": {
      "top": 2.0,
      "bottom": 2.0,
      "left": 2.0,
      "right": 2.0
    },
    "font":{
      "font": "Helvetica",
      "size": 16,
      "attributes": [
        "PLAIN"
      ]
    }
  },
  "series": [
    {
      "lineWidth": 1,
      "color": "#00A9F2",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 1,
      "color": "#0B2B4C",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 1,
      "color": "#85152D",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 1,
      "color": "#49740D",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },

    {
      "lineWidth": 3,
      "color": "#40C9F7",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 3,
      "color": "#445F7C",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 3,
      "color": "#FEB200",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 3,
      "color": "#C7787F",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 3,
      "color": "#9AB46F",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },

    {
      "lineWidth": 5,
      "color": "#98E3FB",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 5,
      "color": "#91A1B5",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    }
  ],
  "padding": {
    "top": 10,
    "bottom": 10,
    "left": 20,
    "right": 20
  },
  "size": {
    "width": 1000,
    "height": 600
  }
}

=== dreth/kdb-intellij-plugin/resources/blue-eagle-scatter.json
{
  "type" : "SCATTER",
  "id": "Blue Eagle Scatter",
  "title": {
    "show": true,
    "text": ""
  },
  "backgroundColor": "#FFFFFF",
  "plotBackgroundColor": "#FFFFFF",
  "domainAxis": {
    "label": {
      "show": false
    },
    "ticks": {
      "showTickLabels": true,
      "showTickMarks": true,
      "tickLabelColor": "#404040",
      "tickLabelFont": {
        "font": "Helvetica",
        "size": 16,
        "attributes": ["PLAIN"]
      }
    }
  },
  "rangeAxis": {
    "label": {
      "show": false
    },
    "ticks": {
      "showTickLabels": true,
      "showTickMarks": true,
      "tickLabelColor": "#404040",
      "tickLabelFont": {
        "font": "Helvetica",
        "size": 16,
        "attributes": ["PLAIN"]
      }
    },
    "range": {
      "autoAdjust": true
    },
    "tickUnit": {
      "autoSelection": true
    }
  },
  "grid": {
    "horizontal": true,
    "vertical": true,
    "horizontalLineColor": "#C0C0C0",
    "verticalLineColor": "#C0C0C0",
    "horizontalLineWidth": 0.5,
    "verticalLineWidth": 0.5,
    "horizontalLineType": "DASHED",
    "verticalLineType": "DASHED"
  },
  "legend": {
    "show": true,
    "backgroundColor": "#FFFFFF",
    "position": "BOTTOM",
    "margin": {
      "top": 2.0,
      "bottom": 2.0,
      "left": 2.0,
      "right": 2.0
    },
    "font":{
      "font": "Helvetica",
      "size": 16,
      "attributes": [
        "PLAIN"
      ]
    }
  },
  "series": [
    {
      "color": "#00A9F2",
      "visibleInLegend": true,
      "show": true,
      "fillColor": "#00A9F2",
      "outlineColor": "#00A9F2"
    },
    {
      "color": "#0B2B4C",
      "visibleInLegend": true,
      "show": true,
      "fillColor": "#0B2B4C",
      "outlineColor": "#0B2B4C"
    },
    {
      "color": "#85152D",
      "lineType" : "SOLID",
      "show": true,
      "fillColor": "#85152D",
      "outlineColor": "#85152D"
    },
    {
      "color": "#49740D",
      "lineType" : "SOLID",
      "show": true,
      "fillColor": "#49740D",
      "outlineColor": "#49740D"
    },
    {
      "color": "#40C9F7",
      "lineType" : "SOLID",
      "show": true,
      "fillColor": "#40C9F7",
      "outlineColor": "#40C9F7"
    },
    {
      "color": "#445F7C",
      "visibleInLegend": true,
      "show": true,
      "fillColor": "#445F7C",
      "outlineColor": "#445F7C"
    },
    {
      "color": "#FEB200",
      "visibleInLegend": true,
      "show": true,
      "fillColor": "#FEB200",
      "outlineColor": "#FEB200"
    },
    {
      "color": "#C7787F",
      "lineType" : "SOLID",
      "show": true,
      "fillColor": "#C7787F",
      "outlineColor": "#C7787F"
    },
    {
      "color": "#9AB46F",
      "visibleInLegend": true,
      "show": true,
      "fillColor": "#9AB46F",
      "outlineColor": "#9AB46F"
    },

    {
      "color": "#98E3FB",
      "visibleInLegend": true,
      "show": true,
      "fillColor": "#98E3FB",
      "outlineColor": "#98E3FB"
    },
    {
      "color": "#91A1B5",
      "visibleInLegend": true,
      "show": true,
      "fillColor": "#91A1B5",
      "outlineColor": "#91A1B5"
    }
  ],
  "padding": {
    "top": 10,
    "bottom": 10,
    "left": 20,
    "right": 20
  },
  "size": {
    "width": 1000,
    "height": 600
  }
}

=== dreth/kdb-intellij-plugin/resources/first-class-lines.json
{
  "type" : "LINE",
  "id": "First-Class Lines",
  "title": {
    "show": true,
    "text": "",
    "font": {
      "font": "Amplitude",
      "size": 16,
      "attributes": [
        "PLAIN"
      ]
    }
  },
  "backgroundColor": "#FFFFFF",
  "plotBackgroundColor": "#FFFFFF",
  "domainAxis": {
    "label": {
      "show": false
    },
    "ticks": {
      "showTickLabels": true,
      "showTickMarks": true,
      "tickLabelColor": "#404040",
      "tickLabelFont": {
        "font": "Amplitude",
        "size": 16,
        "attributes": ["PLAIN"]
      }
    }
  },
  "rangeAxis": {
    "label": {
      "show": false
    },
    "ticks": {
      "showTickLabels": true,
      "showTickMarks": true,
      "tickLabelColor": "#404040",
      "tickLabelFont": {
        "font": "Amplitude",
        "size": 16,
        "attributes": ["PLAIN"]
      }
    },
    "range": {
      "autoAdjust": true
    },
    "tickUnit": {
      "autoSelection": true
    }
  },
  "grid": {
    "horizontal": false,
    "vertical": false,
    "horizontalLineColor": "#C0C0C0",
    "verticalLineColor": "#C0C0C0",
    "horizontalLineWidth": 0.5,
    "verticalLineWidth": 0.5,
    "horizontalLineType": "DASHED",
    "verticalLineType": "DASHED"
  },
  "legend": {
    "show": true,
    "backgroundColor": "#FFFFFF",
    "position": "BOTTOM",
    "margin": {
      "top": 2.0,
      "bottom": 2.0,
      "left": 2.0,
      "right": 2.0
    },
    "font":{
      "font": "Amplitude",
      "size": 16,
      "attributes": [
        "PLAIN"
      ]
    }
  },
  "series": [
    {
      "lineWidth": 2,
      "color": "#005394",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 2,
      "color": "#33261D",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 2,
      "color": "#AC0020",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 3,
      "color": "#7D7570",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 1,
      "color": "#4E5E28",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 1,
      "color": "#3E6C9F",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 1,
      "color": "#361F65",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 3,
      "color": "#B2C23D",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },

    {
      "lineWidth": 3,
      "color": "#6693BE",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 3,
      "color": "#8E7DAA",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 3,
      "color": "#6E1547",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 3,
      "color": "#905A25",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 3,
      "color": "#DA749E",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },

    {
      "lineWidth": 3,
      "color": "#E47A34",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    },
    {
      "lineWidth": 3,
      "color": "#CF2628",
      "lineType" : "SOLID",
      "visibleInLegend": true,
      "show": true
    }
  ],
  "padding": {
    "top": 10,
    "bottom": 10,
    "left": 20,
    "right": 20
  },
  "size": {
    "width": 1000,
    "height": 600
  }
}
